### ISSUE TITLE
Fix metrics key/field names

### ISSUE THREAD

**Issue by lucasmoten** [DecipherNow/gm-fabric-go#213] opened 2018-04-02 18:43 UTC
Reference: https://github.com/DecipherNow/gm-fabric-dashboard/issues/1785

> Go routine metrics don't show up in the main dashboard due to incorrect naming. The dashboard is expecting go_metrics/runtime/num_goroutines but the metric (seen in the explorer) is simply `go_metrics/num_goroutines

I propose these adjustments where needed
- [ ] Fabric code generation
  - [ ] Determine if driven by the code generation for services and if so
  - [ ] Fix the generation to use the appropriate field name. Presumably, that is `go_metrics/runtime/num_goroutines`
- [ ] Identify affected backend services
  - [ ] Regenerate the service base with update fabric code gen from above
  - [ ] Bring over implementation logic
  - [ ] rebuild binaries and containers through CI processes

This shouldn't be a dashboard fix UNTIL there is some versioning that is standardized.  To that end, if this is going to get enacted (now, or shortly after is a good time for that), then augment the above with

- [ ] Formally define the metrics schema with version identifier so that anyone implementing services can adhere to it
- [ ] Fabric generation, add in appropriate field to denote the version of the metrics schema
- [ ] Regenerate all the services with  reimplementation, build, packaging, etc.
- [ ] Update dashboard to recognize that specific metrics schema version, treating accordingly with any normalization mappings.

**Comment by spmcbride1201** [comment] 2018-04-02 20:44
This PR is relevant to the discussion: https://github.com/DecipherNow/gm-fabric-go/pull/207

**Comment by dougfort** [comment] 2018-04-03 12:10
I am able to reproduce this by forcing a blank host name into the go-metrics configuration.
```go
	sink := gmfabricsink.New(metricsChan)
	gmConfig := gometrics.DefaultConfig("test_service")
	gmConfig.HostName = ""
	logger.Debug().Msgf("gmConfig = %+v", gmConfig)
	gm, err := gometrics.NewGlobal(gmConfig, sink)
```
```json
	"go_metrics/sys_bytes": 7211256.000000,
	"go_metrics/total_gc_pause_ns": 0.000000,
	"go_metrics/total_gc_runs": 0.000000,
	"go_metrics/queues/task-pullblob/length": 350.000000,
	"go_metrics/queues/task-s3push/length": 1203.000000,
	"go_metrics/alloc_bytes": 1728096.000000,
	"go_metrics/malloc_count": 15741.000000,
	"go_metrics/free_count": 1512.000000,
	"go_metrics/heap_objects": 14229.000000,
	"go_metrics/queues/task-pushblob/length": 22.000000,
	"go_metrics/queues/task-s3pull/length": 7.000000,
	"go_metrics/num_goroutines": 20.000000
``` 

As an expedient, we could force a host name there. It could  be anything. We're stripping it out anyway. 

However, this one:

**Comment by dougfort** [comment] 2018-04-03 15:50
This PR adds a version to the JSON output: https://github.com/DecipherNow/gm-fabric-go/pull/207
```json
{
	"grey-matter-metrics-version": "1.0.0",
	"Total/requests": 10,
	"HTTP/requests": 0,
	"HTTPS/requests": 0,
	"RPC/requests": 10,
	"RPC_TLS/requests": 0,
	"function/CatalogStream/requests": 5,
```

**Comment by bushidocodes** [comment] 2018-04-18 17:06
What's the status for this one? Can some of the checkboxes in @lucasmoten's original list get checked?

**Comment by dougfort** [comment] 2018-04-18 17:15
The original problem was caused by using a blank service name.
```go
viper.GetString("service-name")
```
returned an empty string.
I don't think those checkboxes actually apply to the situation.

We do not currently have the capability to update generated code. I have some ideas about that. https://github.com/DecipherNow/gm-fabric-templates/issues/45

I have added https://github.com/DecipherNow/gm-fabric-templates/pull/44 to check for the specific problem.

**Comment by rfielding** [comment] 2018-04-20 13:17
I have normal gometrics showing up in the dashboard.  The default settings explicitly sends everything to a black-hole sink.  Once that is overridden, all metrics written globally are attached to go_metrics.

**Comment by alecholmez** [comment] 2018-05-03 17:58
What's the status of this issue?

**Comment by alecholmez** [comment] 2018-06-22 14:15
Closing dead issue

**Closed by alecholmez** 2018-06-22 14:15 UTC
Labels: Priority-High, bug
