### ISSUE TITLE
gateway_serve_anonymous_arrays problems

### ISSUE THREAD

**Issue by Minger** [DecipherNow/gm-fabric-go#223] opened 2018-04-20 21:53 UTC
When `gateway_serve_anonymous_arrays = true`, a request for a png image file to a service running `v0.1.4` returns 206 partial request error.

When `gateway_serve_anonymous_arrays = false`, that request succeeds 200.

In the first case, the browser sends a request with a header of `Range: bytes 32768-32768`, content size 1 byte when the image is actually a few kilobytes in size.  Seems that `true` clobbers headers in the request handling or alters the request negotiation.

**Comment by dougfort** [comment] 2018-04-21 01:02
Caused by the fix for this https://github.com/DecipherNow/gm-fabric-go/issues/160. I will investigate.

**Closed** 2018-04-23 16:54 UTC
Labels: bug
